"""Comprehensive instrument configuration with FundingPips leverage."""
from typing import Dict, Any

INSTRUMENTS: Dict[str, Dict[str, Any]] = {
    "NQ1!": {
        "label": "NQ1! (Nasdaq)",
        "ticker": "^IXIC",
        "yahoo": "NQ=F",
        "kind": "index",
        "digits": 2,
        "pip_digits": 1,
        "pip_val": 1.0,
        "mult": 20,
        "contract_size": 20,
        "leverage": 100,
        "tick_size": 0.25,
        "tick_value": 5.0,
        "min_qty": 0.01,
        "qty_step": 0.01,
        "point_value": 0.5,
        "unit": "contract",
        "session_open_utc": "14:30",
        "session_close_utc": "21:00",
    },
    "ES1!": {
        "label": "ES1! (S&P 500)",
        "ticker": "^GSPC",
        "yahoo": "ES=F",
        "kind": "index",
        "digits": 2,
        "pip_digits": 1,
        "pip_val": 1.0,
        "mult": 50,
        "contract_size": 50,
        "leverage": 100,
        "tick_size": 0.25,
        "tick_value": 12.5,
        "min_qty": 0.01,
        "qty_step": 0.01,
        "point_value": 0.25,
        "unit": "contract",
        "session_open_utc": "14:30",
        "session_close_utc": "21:00",
    },
    "EURUSD": {
        "label": "EUR/USD",
        "ticker": "EURUSD=X",
        "yahoo": "EURUSD=X",
        "kind": "fx",
        "digits": 5,
        "pip_digits": 4,
        "pip_val": 10.0,
        "mult": 100000,
        "contract_size": 100000,
        "leverage": 100,
        "tick_size": 0.00001,
        "tick_value": 1.0,
        "min_qty": 0.01,
        "qty_step": 0.01,
        "point_value": 100000.0,
        "unit": "lot",
        "session_open_utc": "22:00",
        "session_close_utc": "21:00",
    },
    "GBPUSD": {
        "label": "GBP/USD",
        "ticker": "GBPUSD=X",
        "yahoo": "GBPUSD=X",
        "kind": "fx",
        "digits": 5,
        "pip_digits": 4,
        "pip_val": 10.0,
        "mult": 100000,
        "contract_size": 100000,
        "leverage": 100,
        "tick_size": 0.00001,
        "tick_value": 1.0,
        "min_qty": 0.01,
        "qty_step": 0.01,
        "point_value": 100000.0,
        "unit": "lot",
        "session_open_utc": "22:00",
        "session_close_utc": "21:00",
    },
    "XAUUSD": {
        "label": "XAU/USD (Gold)",
        "ticker": "XAUUSD=X",
        "yahoo": "GC=F",
        "kind": "metal",
        "digits": 2,
        "pip_digits": 2,
        "pip_val": 10.0,
        "mult": 100,
        "contract_size": 100,
        "leverage": 10,
        "tick_size": 0.01,
        "tick_value": 1.0,
        "min_qty": 0.01,
        "qty_step": 0.01,
        "point_value": 100.0,
        "unit": "oz",
        "session_open_utc": "22:00",
        "session_close_utc": "21:00",
    },
    "USDJPY": {
        "label": "USD/JPY",
        "ticker": "USDJPY=X",
        "yahoo": "USDJPY=X",
        "kind": "fx",
        "digits": 3,
        "pip_digits": 2,
        "pip_val": 9.1,
        "mult": 100000,
        "contract_size": 100000,
        "leverage": 100,
        "tick_size": 0.001,
        "tick_value": 100.0,
        "min_qty": 0.01,
        "qty_step": 0.01,
        "point_value": 1000.0,
        "unit": "lot",
        "session_open_utc": "22:00",
        "session_close_utc": "21:00",
    },
    "BTCUSD": {
        "label": "BTC/USD",
        "ticker": "BTC-USD",
        "yahoo": "BTC-USD",
        "kind": "crypto",
        "digits": 0,
        "pip_digits": 0,
        "pip_val": 1.0,
        "mult": 1,
        "contract_size": 1,
        "leverage": 30,
        "tick_size": 1.0,
        "tick_value": 1.0,
        "min_qty": 0.001,
        "qty_step": 0.001,
        "point_value": 1.0,
        "unit": "coin",
        "session_open_utc": "00:00",
        "session_close_utc": "23:59",
    },
    "CL1!": {
        "label": "CL1! (Crude Oil)",
        "ticker": "CL=F",
        "yahoo": "CL=F",
        "kind": "commodity",
        "digits": 2,
        "pip_digits": 2,
        "pip_val": 10.0,
        "mult": 1000,
        "contract_size": 1000,
        "leverage": 20,
        "tick_size": 0.01,
        "tick_value": 10.0,
        "min_qty": 0.01,
        "qty_step": 0.01,
        "point_value": 100.0,
        "unit": "contract",
        "session_open_utc": "14:00",
        "session_close_utc": "21:30",
    },
}

KIND_LABELS = {
    "fx": "Forex",
    "index": "Index",
    "metal": "Metal",
    "crypto": "Crypto",
    "commodity": "Commodity",
}


def get_instrument(symbol: str) -> Dict[str, Any]:
    """Get instrument config by symbol."""
    return INSTRUMENTS.get(symbol.upper(), INSTRUMENTS.get(symbol, {}))


def get_all_instruments() -> Dict[str, Dict[str, Any]]:
    """Get all instrument configs."""
    return INSTRUMENTS


def get_kind_label(kind: str) -> str:
    """Get human-readable label for kind."""
    return KIND_LABELS.get(kind, kind.title())
