import { useState, useRef } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { AIChatPanel } from '@/components/AIChatPanel'
import { useKnowledgeBase } from '@/hooks/useKnowledgeBase'
import {
  Youtube, FileText, Trash2, Search, Loader2, BookOpen,
  Tag, Clock, Eye, BarChart3, Brain, CheckCircle, AlertCircle,
  ChevronDown, ChevronUp, ExternalLink, Activity, Hash,
  Zap, MessageSquare, X, Play, Download, GraduationCap, Filter
} from 'lucide-react'

interface IngestLog {
  id: string
  time: string
  message: string
  type: 'info' | 'success' | 'error' | 'warning'
}

function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function buildSourceMarkdown(source: any): string {
  const analysis = source.analysis || {}
  const tags = (source.tags || []).join(', ')
  const concepts = (source.concepts || []).join(', ')
  const metadata = source.metadata || {}

  let summary = analysis.summary || 'No summary available.'
  // Ensure summary is meaningful and detailed
  if (summary.length < 100) {
    summary = summary + '\n\n*(Summary was too short — consider re-analyzing the transcript for better insights.)*'
  }

  return `# ${source.title}

**Source:** ${source.url || 'manual-entry'}  
**Type:** ${source.source_type}  
**Date:** ${source.created_at || 'N/A'}  
**Duration:** ${metadata.duration ? Math.floor(metadata.duration / 60) + 'm' : 'N/A'}  
**Tags:** ${tags || 'None'}  
**Concepts:** ${concepts || 'None'}

---

## Summary
${summary}

## Key Concepts
${analysis.key_concepts?.join(', ') || concepts || 'None identified.'}

## Trading Insights
${analysis.trading_insights || 'No trading insights extracted.'}

## Actionable Takeaways
${(analysis.actionable_takeaways || []).map((t: string, i: number) => `${i + 1}. ${t}`).join('\n') || 'None recorded.'}

## Key Timestamps
${(analysis.timestamps || []).slice(0, 10).map((ts: any) => `- \`${ts.time}\` — ${ts.concept}: ${ts.description}`).join('\n') || 'No timestamps extracted.'}

## Transcript
${source.transcript || 'No transcript available.'}

---

*Generated by ICT Trading OS Knowledge Base*
`
}

function buildAllSourcesMarkdown(sources: any[]): string {
  const parts = [
    '# ICT Trading OS — Agent Training Knowledge Base',
    '',
    `Total Sources: ${sources.length}  \nGenerated: ${new Date().toISOString()}`,
    '',
    '---',
    '',
  ]

  for (const source of sources) {
    parts.push(buildSourceMarkdown(source))
    parts.push('\n---\n')
  }

  return parts.join('\n')
}

// Minimum quality thresholds for filtering "meaningful" content
const MEANINGFUL_MIN_WORDS = 150
const MEANINGFUL_MIN_RELEVANCE = 'medium' // high or medium

function isMeaningful(source: any): boolean {
  const analysis = source.analysis || {}
  const wordCount = analysis.word_count || (source.transcript || '').split(/\s+/).length
  const relevance = analysis.ict_relevance || 'low'
  
  const hasEnoughWords = wordCount >= MEANINGFUL_MIN_WORDS
  const hasRelevance = relevance === 'high' || relevance === 'medium'
  const hasSummary = !!analysis.summary && analysis.summary.length > 50
  const hasConcepts = (analysis.key_concepts || []).length > 0

  return hasEnoughWords && hasRelevance && (hasSummary || hasConcepts)
}

export default function Knowledge() {
  const [youtubeUrl, setYoutubeUrl] = useState('')
  const [transcriptText, setTranscriptText] = useState('')
  const [tags, setTags] = useState('')
  const [manualTitle, setManualTitle] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [searchResults, setSearchResults] = useState<any[]>([])
  const [isSearching, setIsSearching] = useState(false)
  const [expandedSource, setExpandedSource] = useState<string | null>(null)
  const [useAI, setUseAI] = useState(true)
  const [ingestLogs, setIngestLogs] = useState<IngestLog[]>([])
  const [videoPreview, setVideoPreview] = useState<string | null>(null)
  const [showOnlyMeaningful, setShowOnlyMeaningful] = useState(false)
  const [minWordCount, setMinWordCount] = useState(150)
  const [relevanceFilter, setRelevanceFilter] = useState<string>('all')

  const logRef = useRef<HTMLDivElement>(null)

  const {
    sources, status, isLoading, isTranscribing, lastResult,
    addSource, autoTranscribe, deleteSource, refresh
  } = useKnowledgeBase()

  const addLog = (message: string, type: IngestLog['type'] = 'info') => {
    const log: IngestLog = {
      id: Math.random().toString(36).slice(2),
      time: new Date().toLocaleTimeString(),
      message,
      type,
    }
    setIngestLogs((prev) => [...prev, log])
    setTimeout(() => {
      logRef.current?.scrollTo({ top: logRef.current.scrollHeight, behavior: 'smooth' })
    }, 50)
  }

  const clearLogs = () => setIngestLogs([])

  const extractVideoId = (url: string): string | null => {
    const match = url.match(/(?:v=|\/embed\/|youtu\.be\/|\/v\/|\/watch\?v=)([a-zA-Z0-9_-]{11})/)
    return match ? match[1] : null
  }

  const handleYouTubeUrlChange = (url: string) => {
    setYoutubeUrl(url)
    const vid = extractVideoId(url)
    setVideoPreview(vid)
  }

  const handleAddSource = async () => {
    if (!manualTitle || !transcriptText) return
    addLog(`Adding manual source: "${manualTitle}"`, 'info')
    try {
      await addSource(manualTitle, 'manual-entry', transcriptText, tags)
      addLog(`Manual source "${manualTitle}" added successfully`, 'success')
      setManualTitle('')
      setTranscriptText('')
    } catch (e) {
      addLog('Failed to add manual source', 'error')
    }
  }

  const handleAutoTranscribe = async () => {
    if (!youtubeUrl.trim()) return
    addLog(`Starting transcription for: ${youtubeUrl}`, 'info')
    try {
      const result = await autoTranscribe(youtubeUrl.trim(), tags, useAI)
      if (result) {
        addLog(`Transcription complete: ${result.source_count} sources created`, 'success')
        if (result.failed.length > 0) {
          addLog(`${result.failed.length} source(s) failed`, 'warning')
        }
      } else {
        addLog('Transcription returned no result', 'warning')
      }
      setYoutubeUrl('')
      setVideoPreview(null)
    } catch (e: any) {
      addLog(`Transcription failed: ${e?.message || 'Unknown error'}`, 'error')
    }
  }

  const handleSearch = async () => {
    if (!searchQuery.trim()) return
    setIsSearching(true)
    addLog(`Searching knowledge base: "${searchQuery}"`, 'info')
    try {
      const { kbApi } = await import('@/api/client')
      const response = await kbApi.searchEmbeddings(searchQuery, 8)
      setSearchResults(response.data || [])
      addLog(`Found ${(response.data || []).length} results`, 'success')
    } catch (e) {
      console.error('Search failed:', e)
      addLog('Vector search failed, falling back to text search', 'warning')
      try {
        const { kbApi } = await import('@/api/client')
        const response = await kbApi.search(searchQuery)
        const results = (response.data || []).map((s: any) => ({
          source_title: s.title,
          source_url: s.url,
          chunk_text: s.transcript?.substring(0, 300) || '',
          score: 1.0,
        }))
        setSearchResults(results)
        addLog(`Found ${results.length} results (text search)`, 'success')
      } catch (e2) {
        console.error('Fallback search failed:', e2)
        addLog('Search failed completely', 'error')
      }
    } finally {
      setIsSearching(false)
    }
  }

  const handleQuickQuery = (query: string) => {
    setSearchQuery(query)
    setTimeout(() => {
      handleSearchForQuery(query)
    }, 100)
  }

  const handleSearchForQuery = async (query: string) => {
    if (!query.trim()) return
    setIsSearching(true)
    try {
      const { kbApi } = await import('@/api/client')
      const response = await kbApi.searchEmbeddings(query, 8)
      setSearchResults(response.data || [])
    } catch (e) {
      try {
        const { kbApi } = await import('@/api/client')
        const response = await kbApi.search(query)
        const results = (response.data || []).map((s: any) => ({
          source_title: s.title,
          source_url: s.url,
          chunk_text: s.transcript?.substring(0, 300) || '',
          score: 1.0,
        }))
        setSearchResults(results)
      } catch (e2) {}
    } finally {
      setIsSearching(false)
    }
  }

  const handleExportSource = (source: any) => {
    const md = buildSourceMarkdown(source)
    const filename = `${source.title.replace(/[^a-z0-9]/gi, '_').substring(0, 40)}.md`
    downloadMarkdown(filename, md)
    addLog(`Exported "${source.title}" to ${filename}`, 'success')
  }

  const handleLearnSource = (source: any) => {
    const md = buildSourceMarkdown(source)
    const filename = `${source.title.replace(/[^a-z0-9]/gi, '_').substring(0, 40)}_agent.md`
    downloadMarkdown(filename, md)
    addLog(`Learned "${source.title}" — saved agent training file`, 'success')
  }

  const handleExportAll = () => {
    const meaningful = filteredSources()
    if (meaningful.length === 0) {
      addLog('No meaningful sources to export', 'warning')
      return
    }
    const md = buildAllSourcesMarkdown(meaningful)
    const filename = `ictos_knowledge_base_${new Date().toISOString().split('T')[0]}.md`
    downloadMarkdown(filename, md)
    addLog(`Exported ${meaningful.length} sources to ${filename}`, 'success')
  }

  const filteredSources = () => {
    if (!showOnlyMeaningful && relevanceFilter === 'all') return sources
    return sources.filter((s: any) => {
      const analysis = s.analysis || {}
      const wordCount = analysis.word_count || (s.transcript || '').split(/\s+/).length
      const relevance = analysis.ict_relevance || 'low'
      
      const passesWordCount = wordCount >= minWordCount
      const passesRelevance = relevanceFilter === 'all' || relevance === relevanceFilter || (relevanceFilter === 'medium' && relevance === 'high')
      const hasContent = !!analysis.summary || (analysis.key_concepts || []).length > 0
      
      if (!showOnlyMeaningful) return passesRelevance && hasContent
      return passesWordCount && passesRelevance && hasContent
    })
  }

  const formatDuration = (seconds: number) => {
    if (!seconds) return 'N/A'
    const m = Math.floor(seconds / 60)
    const s = seconds % 60
    return `${m}m ${s}s`
  }

  const formatDate = (dateStr: string | undefined) => {
    if (!dateStr) return 'N/A'
    try {
      return new Date(dateStr).toLocaleDateString()
    } catch {
      return dateStr
    }
  }

  const logColor = (type: IngestLog['type']) => {
    switch (type) {
      case 'success': return 'text-emerald-400'
      case 'error': return 'text-red-400'
      case 'warning': return 'text-amber-400'
      default: return 'text-blue-400'
    }
  }

  const quickQueries = [
    { label: 'What is FVG?', query: 'What is a Fair Value Gap?' },
    { label: 'Explain Power of 3', query: 'Explain Power of 3' },
    { label: 'Kill Zones', query: 'What are kill zones?' },
    { label: 'My Sources', query: 'Summarize my added sources' },
  ]

  const displaySources = filteredSources()
  const meaningfulCount = sources.filter((s: any) => isMeaningful(s)).length

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
          <Brain className="w-6 h-6 text-primary" />
          Knowledge Base
        </h1>
        <p className="text-muted-foreground">
          Ingest YouTube videos, transcripts, and build your ICT knowledge library for agent training
        </p>
      </div>

      {/* Stats Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Card>
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <div className="text-xs text-muted-foreground">Total Sources</div>
              <div className="text-xl font-bold">{status?.source_count ?? sources.length}</div>
            </div>
            <BookOpen className="w-5 h-5 text-primary/60" />
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <div className="text-xs text-muted-foreground">Meaningful</div>
              <div className="text-xl font-bold text-emerald-400">{meaningfulCount}</div>
            </div>
            <CheckCircle className="w-5 h-5 text-emerald-400/60" />
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <div className="text-xs text-muted-foreground">Concepts</div>
              <div className="text-xl font-bold">{status?.concept_count ?? 0}</div>
            </div>
            <Hash className="w-5 h-5 text-amber-400/60" />
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center justify-between">
            <div>
              <div className="text-xs text-muted-foreground">Videos</div>
              <div className="text-xl font-bold">{status?.youtube_source_count ?? 0}</div>
            </div>
            <Youtube className="w-5 h-5 text-red-500/60" />
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        {/* Left Column: Ingestion & Sources */}
        <div className="space-y-4">
          {/* YouTube Auto-Transcribe */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Youtube className="w-5 h-5 text-red-500" />
                YouTube Auto-Transcribe
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">YouTube URL (video, playlist, or channel)</label>
                <input
                  type="text"
                  placeholder="https://www.youtube.com/watch?v=..."
                  value={youtubeUrl}
                  onChange={(e) => handleYouTubeUrlChange(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md bg-background text-sm"
                />
              </div>

              {/* YouTube Video Preview */}
              {videoPreview && (
                <div className="rounded-md overflow-hidden border border-border bg-black">
                  <div className="relative aspect-video">
                    <img
                      src={`https://img.youtube.com/vi/${videoPreview}/mqdefault.jpg`}
                      alt="Video thumbnail"
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 flex items-center justify-center">
                      <a
                        href={`https://www.youtube.com/watch?v=${videoPreview}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="bg-red-600 text-white rounded-full p-2 hover:bg-red-700 transition-colors"
                      >
                        <Play className="w-5 h-5 fill-current" />
                      </a>
                    </div>
                    <div className="absolute bottom-2 left-2 bg-black/70 px-2 py-0.5 rounded text-xs text-white">
                      Preview
                    </div>
                  </div>
                </div>
              )}

              <div className="space-y-2">
                <label className="text-sm font-medium">Tags (comma-separated)</label>
                <input
                  type="text"
                  placeholder="ICT, FVG, liquidity, ..."
                  value={tags}
                  onChange={(e) => setTags(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md bg-background text-sm"
                />
                <div className="flex flex-wrap gap-1">
                  {['FVG', 'OTE', 'Kill Zones', 'Liquidity', 'HTF MSS'].map((tag) => (
                    <button
                      key={tag}
                      onClick={() => setTags((prev) => (prev ? prev + ', ' + tag : tag))}
                      className="px-2 py-0.5 rounded-full text-[10px] border border-border bg-muted hover:border-primary/40 hover:bg-primary/5 transition-colors"
                    >
                      {tag}
                    </button>
                  ))}
                </div>
              </div>
              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="useAI"
                  checked={useAI}
                  onChange={(e) => setUseAI(e.target.checked)}
                  className="rounded border-gray-300"
                />
                <label htmlFor="useAI" className="text-sm flex items-center gap-1">
                  <Brain className="w-4 h-4" />
                  Use AI Analysis (LLM-powered summary & insights)
                </label>
              </div>
              <Button
                onClick={handleAutoTranscribe}
                disabled={isTranscribing || !youtubeUrl.trim()}
                className="w-full"
              >
                {isTranscribing ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Transcribing & Analyzing...
                  </>
                ) : (
                  <>
                    <Youtube className="w-4 h-4 mr-2" />
                    Auto-Transcribe & Ingest
                  </>
                )}
              </Button>

              {/* Last result summary */}
              {lastResult && (
                <div className="mt-3 p-3 bg-muted rounded-md text-sm space-y-2">
                  <div className="flex items-center gap-2 font-medium">
                    {lastResult.failed.length === 0 ? (
                      <CheckCircle className="w-4 h-4 text-green-500" />
                    ) : (
                      <AlertCircle className="w-4 h-4 text-yellow-500" />
                    )}
                    {lastResult.url_type === 'channel' ? 'Channel' : lastResult.url_type === 'playlist' ? 'Playlist' : 'Video'} analyzed
                    ({lastResult.source_count} sources created)
                  </div>
                  {lastResult.channel_analysis && (
                    <div className="text-xs space-y-1">
                      <div>Videos: {lastResult.channel_analysis.videos_analyzed} | Words: {lastResult.channel_analysis.total_words}</div>
                      <div>Sentiment: {lastResult.channel_analysis.dominant_sentiment}</div>
                      <div>Top concepts: {lastResult.channel_analysis.top_concepts.slice(0, 5).map((c: any) => c[0]).join(', ')}</div>
                    </div>
                  )}
                  {lastResult.failed.length > 0 && (
                    <div className="text-xs text-red-500">
                      {lastResult.failed.length} failed: {lastResult.failed.map((f: any) => f.title).join(', ')}
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>

          {/* Manual Entry */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                Manual Transcript Entry
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <input
                type="text"
                placeholder="Title"
                value={manualTitle}
                onChange={(e) => setManualTitle(e.target.value)}
                className="w-full px-3 py-2 border rounded-md bg-background text-sm"
              />
              <textarea
                className="w-full px-3 py-2 border rounded-md bg-background min-h-[100px] text-sm"
                placeholder="Paste transcript or notes here..."
                value={transcriptText}
                onChange={(e) => setTranscriptText(e.target.value)}
              />
              <Button
                onClick={handleAddSource}
                disabled={isLoading || !manualTitle || !transcriptText}
                variant="outline"
                className="w-full"
              >
                {isLoading ? 'Adding...' : 'Add to Knowledge Base'}
              </Button>
            </CardContent>
          </Card>

          {/* Search */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Search className="w-5 h-5" />
                Search Knowledge Base
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder="Search concepts, setups, transcripts..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                  className="flex-1 px-3 py-2 border rounded-md bg-background text-sm"
                />
                <Button onClick={handleSearch} disabled={isSearching || !searchQuery.trim()}>
                  {isSearching ? <Loader2 className="w-4 h-4 animate-spin" /> : <Search className="w-4 h-4" />}
                </Button>
              </div>
              {searchResults.length > 0 && (
                <div className="space-y-2 max-h-[300px] overflow-y-auto">
                  {searchResults.map((result: any, index: number) => (
                    <div key={index} className="p-3 border rounded-md bg-muted/50">
                      <div className="text-sm font-medium flex items-center gap-1">
                        <BookOpen className="w-3 h-3" />
                        {result.source_title || 'Unknown'}
                      </div>
                      <div className="text-xs text-muted-foreground mt-1 line-clamp-3">
                        {result.chunk_text || result.transcript?.substring(0, 200)}
                      </div>
                      <div className="text-xs text-muted-foreground mt-1">
                        Relevance: {result.score?.toFixed(3) || 'N/A'}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Right Column: AI Chat + Stats + Quick Queries + Log */}
        <div className="space-y-4">
          <Card className="h-[500px] flex flex-col">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2">
                <Brain className="w-5 h-5 text-primary" />
                AI Knowledge Chat
              </CardTitle>
            </CardHeader>
            <CardContent className="flex-1 p-0 overflow-hidden">
              <AIChatPanel />
            </CardContent>
          </Card>

          {/* Quick Queries */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-sm">
                <Zap className="w-4 h-4 text-amber-400" />
                Quick Queries
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                {quickQueries.map((qq) => (
                  <button
                    key={qq.label}
                    onClick={() => handleQuickQuery(qq.query)}
                    className="px-3 py-1.5 rounded-md text-xs border border-border bg-muted hover:border-primary/40 hover:bg-primary/5 transition-colors"
                  >
                    {qq.label}
                  </button>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Ingestion Log */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center justify-between text-sm">
                <span className="flex items-center gap-2">
                  <MessageSquare className="w-4 h-4 text-blue-400" />
                  Ingestion Log
                </span>
                <Button variant="ghost" size="sm" onClick={clearLogs} className="h-7 px-2">
                  <X className="w-3 h-3 mr-1" />
                  Clear
                </Button>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div
                ref={logRef}
                className="h-[160px] overflow-y-auto rounded-md bg-muted/50 border border-border p-2 space-y-1 font-mono text-xs"
              >
                {ingestLogs.length === 0 ? (
                  <div className="text-muted-foreground text-center py-6">
                    No activity yet. Add a source or run transcription to see logs.
                  </div>
                ) : (
                  ingestLogs.map((log) => (
                    <div key={log.id} className="flex items-start gap-2">
                      <span className="text-muted-foreground flex-shrink-0">[{log.time}]</span>
                      <span className={logColor(log.type)}>{log.message}</span>
                    </div>
                  ))
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Sources List with Filter Controls */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between">
            <span className="flex items-center gap-2">
              <BookOpen className="w-5 h-5" />
              Sources ({displaySources.length} / {sources.length})
            </span>
            <div className="flex items-center gap-2">
              {/* Filter Controls */}
              <div className="flex items-center gap-2 mr-4">
                <button
                  onClick={() => setShowOnlyMeaningful(!showOnlyMeaningful)}
                  className={`flex items-center gap-1 px-2 py-1 text-xs rounded border transition-colors ${
                    showOnlyMeaningful
                      ? 'bg-primary/10 border-primary text-primary'
                      : 'border-border bg-muted text-muted-foreground hover:text-foreground'
                  }`}
                >
                  <Filter className="w-3 h-3" />
                  Meaningful Only
                </button>
                <select
                  value={relevanceFilter}
                  onChange={(e) => setRelevanceFilter(e.target.value)}
                  className="px-2 py-1 text-xs border rounded-md bg-background"
                >
                  <option value="all">All Relevance</option>
                  <option value="high">High Only</option>
                  <option value="medium">Medium+</option>
                </select>
              </div>
              <Button variant="ghost" size="sm" onClick={refresh}>
                Refresh
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={handleExportAll}
                disabled={displaySources.length === 0}
              >
                <Download className="w-3 h-3 mr-1" />
                Export All .md
              </Button>
            </div>
          </CardTitle>
        </CardHeader>
        <CardContent>
          {sources.length === 0 ? (
            <div className="text-center text-muted-foreground py-8">
              No sources yet. Add a YouTube URL or paste a transcript to get started.
            </div>
          ) : displaySources.length === 0 ? (
            <div className="text-center text-muted-foreground py-8">
              No sources match the current filter. Try adjusting the filter settings.
            </div>
          ) : (
            <div className="space-y-3">
              {displaySources.map((source: any) => {
                const isExpanded = expandedSource === source.id
                const analysis = source.analysis || {}
                const metadata = source.metadata || {}
                const isGood = isMeaningful(source)
                const wordCount = analysis.word_count || (source.transcript || '').split(/\s+/).length

                return (
                  <div key={source.id} className={`border rounded-md overflow-hidden hover:border-foreground/20 transition-colors ${
                    isGood ? 'border-l-4 border-l-emerald-500' : ''
                  }`}>
                    <div
                      className="p-3 flex items-center justify-between cursor-pointer hover:bg-muted/50"
                      onClick={() => setExpandedSource(isExpanded ? null : source.id)}
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        {source.source_type === 'youtube' ? (
                          <Youtube className="w-4 h-4 text-red-500 flex-shrink-0" />
                        ) : (
                          <FileText className="w-4 h-4 flex-shrink-0" />
                        )}
                        <div className="min-w-0">
                          <div className="text-sm font-medium truncate">{source.title}</div>
                          <div className="text-xs text-muted-foreground flex items-center gap-2 flex-wrap">
                            {source.source_type === 'youtube' && (
                              <>
                                <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{formatDuration(metadata.duration || 0)}</span>
                                <span className="flex items-center gap-1"><Eye className="w-3 h-3" />{(metadata.view_count || 0).toLocaleString()}</span>
                                <span>{metadata.channel}</span>
                              </>
                            )}
                            <span className="flex items-center gap-1"><BarChart3 className="w-3 h-3" />{wordCount} words</span>
                            {analysis.ict_relevance && (
                              <span className={`px-1.5 py-0.5 rounded text-xs ${
                                analysis.ict_relevance === 'high' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' :
                                analysis.ict_relevance === 'medium' ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20' :
                                'bg-muted text-muted-foreground border border-border'
                              }`}>
                                {analysis.ict_relevance} relevance
                              </span>
                            )}
                            {isGood && (
                              <span className="flex items-center gap-1 text-xs text-emerald-400">
                                <CheckCircle className="w-3 h-3" /> Meaningful
                              </span>
                            )}
                            {analysis.ai_enhanced && (
                              <span className="flex items-center gap-1 text-xs text-primary">
                                <Brain className="w-3 h-3" /> AI
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 flex-shrink-0">
                        <button
                          onClick={(e) => {
                            e.stopPropagation()
                            handleExportSource(source)
                          }}
                          className="p-1.5 text-muted-foreground hover:text-primary hover:bg-primary/10 rounded-md transition-colors"
                          title="Export .md"
                        >
                          <Download className="w-4 h-4" />
                        </button>
                        <button
                          onClick={(e) => {
                            e.stopPropagation()
                            handleLearnSource(source)
                          }}
                          className="p-1.5 text-muted-foreground hover:text-emerald-400 hover:bg-emerald-500/10 rounded-md transition-colors"
                          title="Learn (save for agent training)"
                        >
                          <GraduationCap className="w-4 h-4" />
                        </button>
                        {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                        <button
                          onClick={(e) => {
                            e.stopPropagation()
                            deleteSource(source.id)
                            addLog(`Deleted source: ${source.title}`, 'warning')
                          }}
                          className="p-1 text-muted-foreground hover:text-destructive"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    {isExpanded && (
                      <div className="p-3 border-t bg-muted/30 space-y-3">
                        {/* Summary */}
                        {analysis.summary && (
                          <div>
                            <div className="text-xs font-semibold uppercase text-muted-foreground mb-1">Summary</div>
                            <div className="text-sm leading-relaxed">{analysis.summary}</div>
                            {analysis.summary.length < 100 && (
                              <div className="text-xs text-amber-400 mt-1">
                                <AlertCircle className="w-3 h-3 inline mr-1" />
                                Summary is very short — consider re-analyzing with AI enabled.
                              </div>
                            )}
                          </div>
                        )}

                        {/* Key Concepts */}
                        {analysis.key_concepts && analysis.key_concepts.length > 0 && (
                          <div>
                            <div className="text-xs font-semibold uppercase text-muted-foreground mb-1">Key Concepts</div>
                            <div className="flex flex-wrap gap-1">
                              {analysis.key_concepts.map((concept: string) => (
                                <span key={concept} className="px-2 py-0.5 bg-primary/10 text-primary rounded-full text-xs border border-primary/10">
                                  {concept}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Timestamps */}
                        {analysis.timestamps && analysis.timestamps.length > 0 && (
                          <div>
                            <div className="text-xs font-semibold uppercase text-muted-foreground mb-1">Key Timestamps</div>
                            <div className="space-y-1">
                              {analysis.timestamps.slice(0, 5).map((ts: any, idx: number) => (
                                <div key={idx} className="text-xs flex items-start gap-2">
                                  <span className="font-mono bg-muted px-1 rounded">{ts.time}</span>
                                  <span className="text-muted-foreground">{ts.concept}: {ts.description?.substring(0, 100)}...</span>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Trading Insights */}
                        {analysis.trading_insights && (
                          <div>
                            <div className="text-xs font-semibold uppercase text-muted-foreground mb-1">Trading Insights</div>
                            <div className="text-sm text-muted-foreground leading-relaxed">{analysis.trading_insights}</div>
                          </div>
                        )}

                        {/* Actionable Takeaways */}
                        {analysis.actionable_takeaways && analysis.actionable_takeaways.length > 0 && (
                          <div>
                            <div className="text-xs font-semibold uppercase text-muted-foreground mb-1">Actionable Takeaways</div>
                            <ul className="list-disc list-inside text-sm space-y-1">
                              {analysis.actionable_takeaways.slice(0, 5).map((item: string, idx: number) => (
                                <li key={idx}>{item}</li>
                              ))}
                            </ul>
                          </div>
                        )}

                        {/* Tags & Concepts */}
                        <div className="flex flex-wrap gap-1">
                          {source.tags?.map((tag: string) => (
                            <span key={tag} className="px-2 py-0.5 bg-muted rounded-full text-xs flex items-center gap-1 border border-border">
                              <Tag className="w-3 h-3" />{tag}
                            </span>
                          ))}
                          {source.concepts?.map((concept: string) => (
                            <span key={concept} className="px-2 py-0.5 bg-primary/10 text-primary rounded-full text-xs border border-primary/10">
                              {concept}
                            </span>
                          ))}
                        </div>

                        {/* Link */}
                        {source.url && source.url !== 'manual-entry' && (
                          <a
                            href={source.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-xs text-primary flex items-center gap-1 hover:underline"
                          >
                            <ExternalLink className="w-3 h-3" /> Open on YouTube
                          </a>
                        )}

                        {/* Stats */}
                        <div className="text-xs text-muted-foreground flex items-center gap-3">
                          <span className="flex items-center gap-1"><BarChart3 className="w-3 h-3" />{wordCount} words</span>
                          <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{formatDate(source.created_at)}</span>
                          {analysis.transcript_source && (
                            <span>Source: {analysis.transcript_source}</span>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
